version: "3.7"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --save “” --appendonly no

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: [ "-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory" ]

  postgres:
    image: postgres:9.6.12
    ports:
      - "5432:5432"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: username
      POSTGRES_PASS: pass
      POSTGRES_DB: dev
      POSTGRES_HOST_AUTH_METHOD: trust